// <auto-generated /> Do not edit manually.
// Source of truth: update the $id field in rexo.schema.json to change the schema version.
// This file is a template processed by MSBuild at build time into obj/SchemaVersion.g.cs.
namespace Rexo.Configuration;

public sealed partial class RepoConfigurationLoader
{
    public const string SupportedSchemaVersion = "__REXO_SCHEMA_VERSION__";
    public const string SupportedRexoSchemaUri = "https://raw.githubusercontent.com/agile-north/rexo/__REXO_SCHEMA_TAG__/rexo.schema.json";
    public const string SupportedPolicySchemaUri = "https://raw.githubusercontent.com/agile-north/rexo/__REXO_SCHEMA_TAG__/policy.schema.json";
    private const string EmbeddedRexoSchemaResourceName = "Rexo.Configuration.rexo.schema.__REXO_SCHEMA_VERSION__.json";
    private const string EmbeddedPolicySchemaResourceName = "Rexo.Configuration.policy.schema.__REXO_SCHEMA_VERSION__.json";
}
